apiVersion: apps/v1
kind: Deployment
metadata:
  name: milkman-bot-deployment
  labels:
    app: milkman-bot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milkman-bot 
  template:
    metadata:
      labels:
        app: milkman-bot 
    spec:
      containers:
      - name: milkman-bot
        image: ghcr.io/charlesndalton/milkman-bot:main
        env:
            - name: RUST_LOG
              value: "INFO"
            - name: INFURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infura-api-key-secret
                  key: INFURA_API_KEY
